src: Add WebRTC development frontend
bluerobotics/mavlink-camera-manager pull request #151
Opened 2022-12-02 14:43 UTC by joaoantoniocardoso

I'll soon merge both interfaces to be easier to deal with the build and HTTP server

2022-12-06 18:41 UTC, patrickelectric requested changes
`package-lock.json` is not necessary if we are using yarn as our package manager

2022-12-06 18:41 UTC, patrickelectric commented on src/stream/webrtc/frontend/src/consumer.ts
> +    return Result.ok(undefined as void);
Is said that we can't return an empty ok

2022-12-06 18:41 UTC, patrickelectric commented on src/stream/webrtc/frontend/src/main.ts
> +import "./assets/main.css";
avoid relative imports, prefer '@'

2022-12-06 18:41 UTC, patrickelectric commented on src/stream/webrtc/frontend/src/manager.ts
> +    this.consumers.clear();
"garbage collector is a good idea"

2022-12-07 18:32 UTC, patrickelectric requested changes

2022-12-07 18:32 UTC, patrickelectric commented on build.rs
> +    println!("cargo:rerun-if-changed=./src/stream/webrtc/frontend/package-lock.json");
use yarn lock over package-lock since we are using yarn

2022-12-07 18:32 UTC, patrickelectric commented on build.rs
> +    if std::env::var("SKIP_NPM").is_err() {
YARN

2022-12-07 18:32 UTC, patrickelectric commented on build.rs
> +fn build_with_npm() {
yarn

2022-12-07 19:45 UTC, joaoantoniocardoso commented on src/stream/webrtc/frontend/src/App.vue
> +      urls: "turn:0.0.0.0:3478",
great catch, it should

2022-12-07 22:01 UTC, patrickelectric approved these changes
Lets continue working over it

2022-12-07 22:02 UTC, merged